### ISSUE TITLE
(Fabric) Weird GUI related crash

### ISSUE THREAD

**Issue by ghost** [JacksonPlayz/mannequins#2] opened 2021-06-15 15:36 UTC
Hi! I've been experiencing this weird GUI related crash.
It happens randomly when opening mannequin's GUI.
Log: https://pastebin.com/qSDvm7jv
Additional info:
Minecraft: 1.16
Java VM: JRE 16 GraalVM
MixinTrace: https://pastebin.com/CGgQwyn5

**Comment by jacksonhardaway** [comment] 2021-06-15 23:07
This seems to be caused by Roughly Enough Items. The crash report doesn't provide enough information for me to determine if there's something wrong with Mannequins, so I'm closing this for now.

**Closed as completed by jacksonhardaway** 2021-06-15 23:07 UTC

**Comment by ghost** [comment] 2021-06-16 02:38
I've got a Not Enough Crashes deobfuscated stack trace. If that helps
https://pastebin.com/7z8kuxs1
